[package]
name = "registration_server"
version = "0.1.0"
authors = ["fabrice <fabrice@desre.org>"]

[features]
ssl = []

[dependencies]
docopt = "0.7"
env_logger = "0.3"
hyper-openssl = "0.2"
iron = "0.5"
iron-cors = { git = "https://github.com/fxbox/iron-cors.git" }
log = "0.3"
params = "0.6"
mount = "0.3"
r2d2 = "0.7"
r2d2_sqlite = "0.2"
rusqlite = "0.11"
redis = "0.8"
router = "0.5"
rustc-serialize = "0.3"
uuid = { version = "0.4", features = ["v4"] }